### PR TITLE
Do not use pushd "" as behavior can be unexpected when used with CDPATH

### LINKED ISSUE #236: Scripts work when users have configured pushd directory
More details to be provided by @jprinet soon.

### PR DESCRIPTION
**Pull request by jprinet**
fix #236

### CODE REVIEW

File: components/scripts/lib/paths.sh [hunk 1]
```diff
@@ -46,9 +46,19 @@ relative_path() {
     printf '%s\n' "$result"
 }
 
+pushd_with_project_dir() {
```
Comment (jthurne) [inline components/scripts/lib/paths.sh:49]: I suggest renaming this to `pushd_to_project_dir` since we're changing directories to the project_dir (it's similar to something like `cd_to_project_dir`).

**Review by jthurne — APPROVED** [review]
LGTM, just a small function naming suggestion.

**Review by etiennestuder — APPROVED** [review]
